### PR TITLE
Updating documentation

### PR DESCRIPTION
**Pull request by pruzanov**
Adding more details explaining how we calculate similarities between samples.

### CODE REVIEW

**Review by lheisler — COMMENTED** [review]
.fin files allow to do two things - produce glyphs with color-coded SNP calls (A,C,T,G) + two shades of gray showing either match with the reference genotype (no call) or zero coverage (too low to make a call), the later detected using output from DepthOfCoverage walker from GATK suite. Below is an excerpt from a random .fin file:

This seems like it is just one thing.  (making glyphs).  What is the other thing.  I assume you mean using these files for calculating distances.  

With respect to coverage, how is this information used?  Is there a hard coverage threshold at any one site that results in the record being marked as N?  if so, what is the threshold?  or is there a default value that can be adjusted with an argument?

you also say that "The newer algorithm which is disabled by default ".  Is this true?  I thought the newer algorithm, using the .fin files, was the default.

**Comment by pruzanov** [comment]
retest this please

**Comment by pruzanov** [comment]
Yes, the newer algorithm is disabled by default but Mei runs all jobs with --mixed-coverage TRUE to enable it in all workflow runs, I believe. We only check if the coverage is zero. There's no threshold.

**Comment by pruzanov** [comment]
retest this please

**Review by lheisler — COMMENTED** [review]
I've corrected a few typos.
I was looking at the bundle of files produced by the swap tool, and its not clear to me what each of these are.   It would be good to describe the information that each contains.

**Review by lheisler — APPROVED** [review]
Looks good, the extra detail helps to understand how this data is being processed

**Pull request merged**
